version: '3.7'

services:
  app:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: themoviepredictor_app
    image: nicookie/themoviepredictor:1.0
    env_file:
      - ../auth.env
      - ../mysql.env
    volumes:
      - ..:/usr/src/themoviepredictor
    networks:
      - database_net
    command: tail -f /dev/null
  database:
    container_name: themoviepredictor_db
    image: mysql:latest
    env_file:
      - ../mysql.env
    networks:
      - database_net
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
      - ../init.db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  adminer:
    container_name: themoviepredictor_adminer
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data: