-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 00:35:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema predictor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `predictor` ;

-- -----------------------------------------------------
-- Schema predictor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `predictor` DEFAULT CHARACTER SET utf8 ;
USE `predictor` ;

-- -----------------------------------------------------
-- Table `predictor`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`roles` ;

CREATE TABLE IF NOT EXISTS `predictor`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`people` ;

CREATE TABLE IF NOT EXISTS `predictor`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movies` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fr_title` VARCHAR(255) CHARACTER SET 'armscii8' NULL,
  `original_title` VARCHAR(45) NULL,
  `adult` TINYINT NULL,
  `budget` INT NULL,
  `duration` INT NULL,
  `release_date` DATE NULL,
  `3d` TINYINT NULL DEFAULT 0,
  `synopsis` TEXT NULL,
  `imdb_id` VARCHAR(255) NULL,
  `score` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `imdb_id_UNIQUE` (`imdb_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movies_people_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movies_people_roles` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movies_people_roles` (
  `movie_id` INT NOT NULL,
  `people_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `people_id_idx` (`people_id` ASC) VISIBLE,
  CONSTRAINT `movie-pr_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_mp_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `predictor`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `people_mr_id`
    FOREIGN KEY (`people_id`)
    REFERENCES `predictor`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movies_origin_countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movies_origin_countries` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movies_origin_countries` (
  `movie_id` INT NOT NULL,
  `country_iso2` CHAR(2) NOT NULL,
  INDEX `country_iso2` (`country_iso2` ASC) VISIBLE,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `movie_oc_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`companies` ;

CREATE TABLE IF NOT EXISTS `predictor`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movies_companies_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movies_companies_roles` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movies_companies_roles` (
  `movie_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `company_id_idx` (`company_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `movie_cr_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_mr_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `predictor`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_mc_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `predictor`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
